"use client";

import { useState } from "react";
import Link from "next/link";

type Photo = { id: string; url: string; originalName: string | null };

type SlotData = {
  photoId: string | null;
  scale?: number;
  x?: number;
  y?: number;
};

type Page = {
  pageNum: number;
  slots: (string | null | SlotData)[];
};

function normalizeSlot(raw: string | null | SlotData | undefined): SlotData {
  if (raw === null || raw === undefined) {
    return { photoId: null, scale: 1, x: 0, y: 0 };
  }
  if (typeof raw === "string") {
    return { photoId: raw, scale: 1, x: 0, y: 0 };
  }
  return {
    photoId: raw.photoId ?? null,
    scale: raw.scale ?? 1,
    x: raw.x ?? 0,
    y: raw.y ?? 0,
  };
}

export default function AdminBookPreview({
  project,
  photos,
  templateLayout,
  adminName,
}: {
  project: {
    id: string;
    title: string;
    templateId: string;
    templateName: string;
    pageCount: number;
    coverColor: string | null;
    status: string;
    autoGenerated: boolean;
    pages: Page[];
    customerName: string;
    customerEmail: string;
    order: {
      id: string;
      bookSize: string;
      coverType: string;
      paperType: string;
      amount: number;
      status: string;
      paymentStatus: string;
      shippingName: string | null;
      shippingPhone: string | null;
      shippingAddress: string | null;
    } | null;
  };
  photos: Photo[];
  templateLayout: string;
  adminName: string;
}) {
  const [currentPage, setCurrentPage] = useState(0);
  const pages = project.pages;
  const page = pages[currentPage];
  const isCover = currentPage === 0;

  const getPhoto = (id: string | null) =>
    id ? photos.find((p) => p.id === id) : null;

  function renderLayout() {
    const slots = page?.slots || [];

    const Slot = ({
      index,
      className = "",
    }: {
      index: number;
      className?: string;
    }) => {
      const slot = normalizeSlot(slots[index]);
      const photo = getPhoto(slot.photoId);
      return (
        <div
          className={`relative rounded overflow-hidden border border-stone-200 bg-stone-100 ${className}`}
        >
          {photo ? (
            <img
              src={photo.url}
              alt={photo.originalName || "Photo"}
              className="absolute inset-0 w-full h-full object-cover"
              style={{
                transform: `scale(${slot.scale ?? 1}) translate(${slot.x ?? 0}%, ${slot.y ?? 0}%)`,
                transformOrigin: "center center",
              }}
            />
          ) : (
            <div className="absolute inset-0 flex items-center justify-center text-stone-300 text-xs">
              Empty
            </div>
          )}
        </div>
      );
    };

    if (isCover) {
      return (
        <div className="w-full h-full flex flex-col">
          <div
            className="flex-1 relative"
            style={{ backgroundColor: project.coverColor || "#1a5f4a" }}
          >
            {normalizeSlot(slots[0]).photoId && (
              <img
                src={getPhoto(normalizeSlot(slots[0]).photoId)?.url}
                alt="Cover"
                className="absolute inset-0 w-full h-full object-cover opacity-90"
                style={{
                  transform: `scale(${normalizeSlot(slots[0]).scale}) translate(${normalizeSlot(slots[0]).x}%, ${normalizeSlot(slots[0]).y}%)`,
                }}
              />
            )}
            <div className="absolute inset-0 flex flex-col items-center justify-center text-white p-6 text-center bg-black/25">
              <h2 className="text-2xl sm:text-3xl font-bold drop-shadow-lg mb-2">
                {project.title}
              </h2>
              <p className="text-sm opacity-90">Chola Chela Photography</p>
            </div>
          </div>
          <div className="h-20 p-2">
            <Slot index={0} className="h-full w-full" />
          </div>
        </div>
      );
    }

    switch (templateLayout) {
      case "single":
        return (
          <div className="w-full h-full p-3">
            <Slot index={0} className="w-full h-full" />
          </div>
        );
      case "hero-plus-two":
      case "wedding":
        return (
          <div className="w-full h-full p-2 grid grid-rows-3 gap-2">
            <Slot index={0} className="row-span-2" />
            <div className="grid grid-cols-2 gap-2">
              <Slot index={1} />
              <Slot index={2} />
            </div>
          </div>
        );
      case "grid-2x2":
        return (
          <div className="w-full h-full p-2 grid grid-cols-2 grid-rows-2 gap-2">
            <Slot index={0} />
            <Slot index={1} />
            <Slot index={2} />
            <Slot index={3} />
          </div>
        );
      case "collage":
        return (
          <div className="w-full h-full p-2 grid grid-cols-3 grid-rows-2 gap-2">
            <Slot index={0} className="col-span-2" />
            <Slot index={1} />
            <Slot index={2} />
            <Slot index={3} />
            <Slot index={4} />
          </div>
        );
      case "family":
        return (
          <div className="w-full h-full p-2 grid grid-cols-3 grid-rows-2 gap-2">
            {[0, 1, 2, 3, 4, 5].map((i) => (
              <Slot key={i} index={i} />
            ))}
          </div>
        );
      default:
        return (
          <div className="w-full h-full p-2 grid grid-cols-2 grid-rows-2 gap-2">
            {slots.map((_, i) => (
              <Slot key={i} index={i} />
            ))}
          </div>
        );
    }
  }

  return (
    <div className="min-h-screen bg-stone-100 flex flex-col">
      <header className="bg-white border-b border-stone-200 sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3 min-w-0">
            <Link
              href="/admin"
              className="text-sm text-stone-500 hover:text-orange-700 shrink-0"
            >
              ← Admin
            </Link>
            <div className="min-w-0">
              <h1 className="font-semibold text-stone-900 truncate">
                {project.title}
              </h1>
              <p className="text-xs text-stone-500">
                {project.templateName} · {project.customerName} · Read-only
                preview
              </p>
            </div>
          </div>
          <span className="text-xs text-stone-400 hidden sm:inline">
            {adminName}
          </span>
        </div>
      </header>

      <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
        {/* Book preview */}
        <div className="flex-1 flex flex-col items-center justify-center p-4 overflow-auto">
          <div className="flex items-center gap-2 mb-3 flex-wrap justify-center">
            <button
              onClick={() => setCurrentPage((p) => Math.max(0, p - 1))}
              disabled={currentPage === 0}
              className="px-3 py-1.5 rounded-lg border border-stone-300 text-sm disabled:opacity-40 bg-white"
            >
              ← Prev
            </button>
            <div className="flex gap-1 max-w-[260px] overflow-x-auto py-1">
              {pages.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setCurrentPage(i)}
                  className={`w-7 h-9 rounded border text-[10px] font-medium shrink-0 ${
                    i === currentPage
                      ? "border-orange-500 bg-orange-50 text-orange-700"
                      : "border-stone-300 bg-white text-stone-500"
                  }`}
                >
                  {i === 0 ? "C" : i}
                </button>
              ))}
            </div>
            <button
              onClick={() =>
                setCurrentPage((p) => Math.min(pages.length - 1, p + 1))
              }
              disabled={currentPage === pages.length - 1}
              className="px-3 py-1.5 rounded-lg border border-stone-300 text-sm disabled:opacity-40 bg-white"
            >
              Next →
            </button>
          </div>

          <div className="bg-white shadow-2xl border border-stone-300 w-full max-w-md aspect-[3/4] overflow-hidden">
            {renderLayout()}
          </div>

          <p className="mt-3 text-xs text-stone-500">
            Page {currentPage + 1} of {pages.length}
            {isCover ? " (Cover)" : ""}
          </p>
        </div>

        {/* Order / customer sidebar */}
        <aside className="w-full lg:w-80 bg-white border-t lg:border-t-0 lg:border-l border-stone-200 p-4 overflow-y-auto shrink-0">
          <h2 className="font-semibold text-stone-800 mb-3">Order details</h2>

          <div className="space-y-3 text-sm">
            <div>
              <div className="text-xs text-stone-500">Customer</div>
              <div className="font-medium">{project.customerName}</div>
              <div className="text-stone-500">{project.customerEmail}</div>
            </div>

            {project.order ? (
              <>
                <div>
                  <div className="text-xs text-stone-500">Print options</div>
                  <div>
                    {project.order.bookSize} · {project.order.coverType} ·{" "}
                    {project.order.paperType}
                  </div>
                  <div className="text-stone-500">
                    {project.pageCount} pages
                  </div>
                </div>
                <div>
                  <div className="text-xs text-stone-500">Amount</div>
                  <div className="font-semibold">
                    K{(project.order.amount / 100).toFixed(2)}
                  </div>
                  <div className="text-xs capitalize text-stone-500">
                    {project.order.paymentStatus} · {project.order.status}
                  </div>
                </div>
                <div>
                  <div className="text-xs text-stone-500">Delivery</div>
                  <div>{project.order.shippingName}</div>
                  <div>{project.order.shippingPhone}</div>
                  <div className="text-stone-500">
                    {project.order.shippingAddress}
                  </div>
                </div>
              </>
            ) : (
              <p className="text-stone-500 text-sm">
                No order placed for this book yet.
              </p>
            )}

            <div className="pt-2 border-t border-stone-100">
              <div className="text-xs text-stone-500">Book status</div>
              <div className="capitalize">{project.status}</div>
              {project.autoGenerated && (
                <div className="text-xs text-orange-600 mt-0.5">Auto-created</div>
              )}
            </div>
          </div>

          <Link
            href="/admin"
            className="mt-6 inline-block w-full text-center py-2.5 rounded-xl border border-stone-200 text-sm font-medium hover:bg-stone-50"
          >
            Back to orders
          </Link>
        </aside>
      </div>
    </div>
  );
}
