import { auth } from "@/lib/auth";
import { redirect, notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getTemplate } from "@/lib/templates";
import AdminBookPreview from "./AdminBookPreview";

export default async function AdminBookPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await auth();
  if (!session?.user?.id) redirect("/login");

  const admin = await prisma.user.findUnique({
    where: { id: session.user.id },
    select: { role: true, name: true },
  });

  if (!admin || admin.role !== "admin") {
    redirect("/dashboard");
  }

  const { id } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
    include: {
      user: { select: { name: true, email: true } },
      order: true,
      projectPhotos: { include: { photo: true } },
    },
  });

  if (!project) notFound();

  const template = getTemplate(project.templateId);
  const pages = JSON.parse(project.pages || "[]");

  const photoMap: Record<
    string,
    { id: string; url: string; originalName: string | null }
  > = {};

  for (const pp of project.projectPhotos) {
    photoMap[pp.photo.id] = {
      id: pp.photo.id,
      url: pp.photo.secureUrl || pp.photo.url,
      originalName: pp.photo.originalName,
    };
  }

  const ownerPhotos = await prisma.photo.findMany({
    where: { userId: project.userId },
  });
  for (const p of ownerPhotos) {
    photoMap[p.id] = {
      id: p.id,
      url: p.secureUrl || p.url,
      originalName: p.originalName,
    };
  }

  return (
    <AdminBookPreview
      project={{
        id: project.id,
        title: project.title,
        templateId: project.templateId,
        templateName: template?.name || project.templateId,
        pageCount: project.pageCount,
        coverColor: project.coverColor,
        status: project.status,
        autoGenerated: project.autoGenerated,
        pages,
        customerName: project.user.name,
        customerEmail: project.user.email,
        order: project.order
          ? {
              id: project.order.id,
              bookSize: project.order.bookSize,
              coverType: project.order.coverType,
              paperType: project.order.paperType,
              amount: project.order.amount,
              status: project.order.status,
              paymentStatus: project.order.paymentStatus,
              shippingName: project.order.shippingName,
              shippingPhone: project.order.shippingPhone,
              shippingAddress: project.order.shippingAddress,
            }
          : null,
      }}
      photos={Object.values(photoMap)}
      templateLayout={template?.layout || "grid-2x2"}
      adminName={admin.name}
    />
  );
}
