"use client";

import { useState, useCallback, useRef } from "react";
import Link from "next/link";
import type { Template } from "@/lib/templates";

type Photo = {
  id: string;
  url: string;
  originalName: string | null;
};

// New richer slot format (backward compatible with old string slots)
type SlotData = {
  photoId: string | null;
  scale: number; // 1 = fit, >1 = zoom in
  x: number; // % offset from center (-50 to 50)
  y: number;
};

type Page = {
  pageNum: number;
  slots: (string | null | SlotData)[];
};

type Project = {
  id: string;
  title: string;
  templateId: string;
  status: string;
  pageCount: number;
  autoGenerated: boolean;
  coverColor: string | null;
  pages: Page[];
};

type DragSource =
  | { type: "library"; photoId: string }
  | { type: "slot"; pageIndex: number; slotIndex: number; photoId: string }
  | null;

function normalizeSlot(raw: string | null | SlotData): SlotData {
  if (raw === null || raw === undefined) {
    return { photoId: null, scale: 1, x: 0, y: 0 };
  }
  if (typeof raw === "string") {
    return { photoId: raw, scale: 1, x: 0, y: 0 };
  }
  return {
    photoId: raw.photoId ?? null,
    scale: raw.scale ?? 1,
    x: raw.x ?? 0,
    y: raw.y ?? 0,
  };
}

function normalizePages(pages: Page[]): Page[] {
  return pages.map((p) => ({
    ...p,
    slots: p.slots.map(normalizeSlot),
  }));
}

export default function EditorClient({
  project: initialProject,
  template,
  photos,
  userName: _userName,
}: {
  project: Project;
  template: Template;
  photos: Photo[];
  userName: string;
}) {
  const [pages, setPages] = useState<Page[]>(() =>
    normalizePages(initialProject.pages)
  );
  const [currentPage, setCurrentPage] = useState(0);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [dragSource, setDragSource] = useState<DragSource>(null);
  const [title, setTitle] = useState(initialProject.title);
  const [coverText, setCoverText] = useState(
    (initialProject as { coverText?: string | null }).coverText || ""
  );
  const [spreadView, setSpreadView] = useState(false);
  const [adjustingSlot, setAdjustingSlot] = useState<number | null>(null);

  // For pan while adjusting
  const panStart = useRef<{ x: number; y: number; slotX: number; slotY: number } | null>(null);

  const page = pages[currentPage];
  const isCover = currentPage === 0;

  const getPhoto = useCallback(
    (id: string | null) => (id ? photos.find((p) => p.id === id) : null),
    [photos]
  );

  const usedPhotoIds = new Set(
    pages.flatMap((p) =>
      p.slots.map((s) => normalizeSlot(s).photoId).filter(Boolean) as string[]
    )
  );

  function updateSlot(slotIndex: number, updates: Partial<SlotData>) {
    setPages((prev) =>
      prev.map((p, i) => {
        if (i !== currentPage) return p;
        const newSlots = p.slots.map((s, si) => {
          const slot = normalizeSlot(s);
          if (si !== slotIndex) return slot;
          return { ...slot, ...updates };
        });
        return { ...p, slots: newSlots };
      })
    );
  }

  function handleDropOnSlot(targetSlotIndex: number) {
    if (!dragSource) return;

    setPages((prev) => {
      const next = prev.map((p) => ({
        ...p,
        slots: p.slots.map(normalizeSlot),
      }));

      if (dragSource.type === "library") {
        next[currentPage].slots[targetSlotIndex] = {
          photoId: dragSource.photoId,
          scale: 1,
          x: 0,
          y: 0,
        };
      } else if (dragSource.type === "slot") {
        const { pageIndex: fromPage, slotIndex: fromSlot, photoId } = dragSource;
        if (fromPage === currentPage && fromSlot === targetSlotIndex) return prev;

        const targetSlot = next[currentPage].slots[targetSlotIndex] as SlotData;
        const sourceSlot = next[fromPage].slots[fromSlot] as SlotData;

        next[currentPage].slots[targetSlotIndex] = {
          ...sourceSlot,
          photoId,
        };
        next[fromPage].slots[fromSlot] = {
          ...targetSlot,
        };
      }
      return next;
    });
    setDragSource(null);
  }

  function clearSlot(slotIndex: number) {
    updateSlot(slotIndex, { photoId: null, scale: 1, x: 0, y: 0 });
    if (adjustingSlot === slotIndex) setAdjustingSlot(null);
  }

  async function handleSave() {
    setSaving(true);
    setMessage("");
    try {
      const res = await fetch(`/api/projects/${initialProject.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pages, title, coverText: coverText || null }),
      });
      if (!res.ok) {
        const data = await res.json();
        setMessage(data.error || "Failed to save");
        return;
      }
      setMessage("Saved successfully!");
      setTimeout(() => setMessage(""), 2500);
    } catch {
      setMessage("Failed to save. Try again.");
    } finally {
      setSaving(false);
    }
  }

  // Pan handlers for adjust mode
  function onPanStart(e: React.MouseEvent | React.TouchEvent, slotIndex: number) {
    const slot = normalizeSlot(page.slots[slotIndex]);
    const clientX = "touches" in e ? e.touches[0].clientX : e.clientX;
    const clientY = "touches" in e ? e.touches[0].clientY : e.clientY;
    panStart.current = { x: clientX, y: clientY, slotX: slot.x, slotY: slot.y };
  }

  function onPanMove(e: React.MouseEvent | React.TouchEvent, slotIndex: number) {
    if (!panStart.current) return;
    const clientX = "touches" in e ? e.touches[0].clientX : e.clientX;
    const clientY = "touches" in e ? e.touches[0].clientY : e.clientY;
    const dx = (clientX - panStart.current.x) / 3;
    const dy = (clientY - panStart.current.y) / 3;
    const newX = Math.max(-50, Math.min(50, panStart.current.slotX + dx));
    const newY = Math.max(-50, Math.min(50, panStart.current.slotY + dy));
    updateSlot(slotIndex, { x: newX, y: newY });
  }

  function onPanEnd() {
    panStart.current = null;
  }

  function renderPageLayout() {
    const slots = page?.slots || [];
    const layout = template.layout;

    const Slot = ({
      index,
      className = "",
    }: {
      index: number;
      className?: string;
    }) => {
      const slot = normalizeSlot(slots[index]);
      const photo = getPhoto(slot.photoId);
      const isAdjusting = adjustingSlot === index;
      const isDraggingThis =
        dragSource?.type === "slot" &&
        dragSource.pageIndex === currentPage &&
        dragSource.slotIndex === index;

      return (
        <div
          draggable={!!photo && !isAdjusting}
          onDragStart={() => {
            if (slot.photoId && !isAdjusting) {
              setDragSource({
                type: "slot",
                pageIndex: currentPage,
                slotIndex: index,
                photoId: slot.photoId,
              });
            }
          }}
          onDragEnd={() => setDragSource(null)}
          onDragOver={(e) => e.preventDefault()}
          onDrop={() => handleDropOnSlot(index)}
          className={`relative rounded overflow-hidden border-2 bg-stone-100 flex items-center justify-center group transition ${
            dragSource && !isAdjusting
              ? "border-orange-400 bg-orange-50/50 border-dashed"
              : isAdjusting
              ? "border-orange-500 ring-2 ring-orange-300"
              : "border-stone-300 border-dashed"
          } ${isDraggingThis ? "opacity-40" : ""} ${className}`}
        >
          {photo ? (
            <>
              <div
                className="absolute inset-0 overflow-hidden"
                onMouseDown={(e) => isAdjusting && onPanStart(e, index)}
                onMouseMove={(e) => isAdjusting && onPanMove(e, index)}
                onMouseUp={onPanEnd}
                onMouseLeave={onPanEnd}
                onTouchStart={(e) => isAdjusting && onPanStart(e, index)}
                onTouchMove={(e) => isAdjusting && onPanMove(e, index)}
                onTouchEnd={onPanEnd}
                style={{ cursor: isAdjusting ? "grab" : "default" }}
              >
                <img
                  src={photo.url}
                  alt={photo.originalName || "Photo"}
                  className="absolute inset-0 w-full h-full object-cover pointer-events-none select-none"
                  style={{
                    transform: `scale(${slot.scale}) translate(${slot.x}%, ${slot.y}%)`,
                    transformOrigin: "center center",
                  }}
                  draggable={false}
                />
              </div>

              {/* Controls overlay */}
              <div className="absolute inset-0 flex flex-col justify-between p-1.5 opacity-0 group-hover:opacity-100 transition pointer-events-none group-hover:pointer-events-auto">
                <div className="flex justify-end gap-1">
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      setAdjustingSlot(isAdjusting ? null : index);
                    }}
                    className={`w-7 h-7 rounded-full text-white text-xs font-bold shadow ${
                      isAdjusting ? "bg-orange-600" : "bg-black/70 hover:bg-orange-600"
                    }`}
                    title="Adjust zoom & position"
                  >
                    ⇄
                  </button>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      clearSlot(index);
                    }}
                    className="w-7 h-7 rounded-full bg-black/70 text-white text-sm font-bold hover:bg-red-600"
                    title="Remove photo"
                  >
                    ×
                  </button>
                </div>
              </div>

              {/* Adjust panel */}
              {isAdjusting && (
                <div
                  className="absolute bottom-0 inset-x-0 bg-black/80 text-white p-2 z-20"
                  onClick={(e) => e.stopPropagation()}
                >
                  <div className="flex items-center gap-2 text-[11px] mb-1">
                    <span className="w-10">Zoom</span>
                    <input
                      type="range"
                      min="1"
                      max="3"
                      step="0.05"
                      value={slot.scale}
                      onChange={(e) =>
                        updateSlot(index, { scale: parseFloat(e.target.value) })
                      }
                      className="flex-1 h-1 accent-orange-500"
                    />
                    <span className="w-8 text-right">{slot.scale.toFixed(1)}x</span>
                  </div>
                  <div className="flex justify-between items-center">
                    <span className="text-[10px] text-stone-300">
                      Drag photo to reposition
                    </span>
                    <button
                      onClick={() => {
                        updateSlot(index, { scale: 1, x: 0, y: 0 });
                      }}
                      className="text-[10px] underline text-orange-300"
                    >
                      Reset
                    </button>
                    <button
                      onClick={() => setAdjustingSlot(null)}
                      className="text-[10px] bg-orange-600 px-2 py-0.5 rounded"
                    >
                      Done
                    </button>
                  </div>
                </div>
              )}
            </>
          ) : (
            <div className="text-center text-stone-400 p-2 pointer-events-none">
              <div className="text-2xl mb-1">📷</div>
              <div className="text-[11px] leading-tight">Drop photo</div>
            </div>
          )}
        </div>
      );
    };

    if (isCover) {
      return (
        <div className="w-full h-full flex flex-col">
          <div
            className="flex-1 rounded-t overflow-hidden relative"
            style={{ backgroundColor: initialProject.coverColor || "#1a5f4a" }}
          >
            {normalizeSlot(slots[0]).photoId ? (
              <img
                src={getPhoto(normalizeSlot(slots[0]).photoId)?.url}
                alt="Cover"
                className="absolute inset-0 w-full h-full object-cover opacity-90"
                style={{
                  transform: `scale(${normalizeSlot(slots[0]).scale}) translate(${normalizeSlot(slots[0]).x}%, ${normalizeSlot(slots[0]).y}%)`,
                }}
              />
            ) : null}
            <div className="absolute inset-0 flex flex-col items-center justify-center text-white p-6 text-center bg-black/20">
              <h2 className="text-2xl sm:text-3xl font-bold drop-shadow-lg mb-2">
                {title}
              </h2>
              {coverText ? (
                <p className="text-sm sm:text-base opacity-95 drop-shadow max-w-xs">
                  {coverText}
                </p>
              ) : (
                <p className="text-sm opacity-90">Chola Chela Photography</p>
              )}
            </div>
          </div>
          <div className="h-20 sm:h-24 p-2">
            <Slot index={0} className="h-full w-full" />
          </div>
        </div>
      );
    }

    switch (layout) {
      case "single":
        return (
          <div className="w-full h-full p-3">
            <Slot index={0} className="w-full h-full" />
          </div>
        );
      case "hero-plus-two":
      case "wedding":
        return (
          <div className="w-full h-full p-2 grid grid-rows-3 gap-2">
            <Slot index={0} className="row-span-2" />
            <div className="grid grid-cols-2 gap-2 row-span-1">
              <Slot index={1} />
              <Slot index={2} />
            </div>
          </div>
        );
      case "grid-2x2":
        return (
          <div className="w-full h-full p-2 grid grid-cols-2 grid-rows-2 gap-2">
            <Slot index={0} />
            <Slot index={1} />
            <Slot index={2} />
            <Slot index={3} />
          </div>
        );
      case "collage":
        return (
          <div className="w-full h-full p-2 grid grid-cols-3 grid-rows-2 gap-2">
            <Slot index={0} className="col-span-2" />
            <Slot index={1} />
            <Slot index={2} />
            <Slot index={3} />
            <Slot index={4} />
          </div>
        );
      case "family":
        return (
          <div className="w-full h-full p-2 grid grid-cols-3 grid-rows-2 gap-2">
            <Slot index={0} />
            <Slot index={1} />
            <Slot index={2} />
            <Slot index={3} />
            <Slot index={4} />
            <Slot index={5} />
          </div>
        );
      default:
        return (
          <div className="w-full h-full p-2 grid grid-cols-2 grid-rows-2 gap-2">
            {slots.map((_, i) => (
              <Slot key={i} index={i} />
            ))}
          </div>
        );
    }
  }

  return (
    <div className="min-h-screen bg-stone-100 flex flex-col">
      <header className="bg-white border-b border-stone-200 sticky top-0 z-50">
        <div className="max-w-5xl mx-auto px-3 sm:px-4 py-3 flex items-center justify-between gap-3">
          <div className="flex items-center gap-3 min-w-0">
            <Link
              href="/dashboard"
              className="text-sm text-stone-500 hover:text-orange-700 shrink-0"
            >
              ← Studio
            </Link>
            <div className="min-w-0">
              <input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="font-semibold text-stone-900 bg-transparent border-b border-transparent hover:border-stone-300 focus:border-orange-500 outline-none w-full max-w-[180px] sm:max-w-xs truncate"
              />
              <p className="text-xs text-stone-500">
                {template.name} · {isCover ? "Cover" : `Page ${currentPage + 1}`} of{" "}
                {pages.length}
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2 sm:gap-3">
            {message && (
              <span
                className={`text-xs sm:text-sm hidden sm:inline ${
                  message.includes("success") ? "text-green-600" : "text-red-600"
                }`}
              >
                {message}
              </span>
            )}
            <Link
              href={`/dashboard/projects/${initialProject.id}/order`}
              className="px-4 py-2 rounded-full border border-orange-600 text-orange-700 text-sm font-medium hover:bg-orange-50 shrink-0"
            >
              Order Book
            </Link>
            <button
              onClick={handleSave}
              disabled={saving}
              className="px-4 py-2 rounded-full bg-orange-700 text-white text-sm font-medium hover:bg-orange-800 disabled:opacity-60 shrink-0"
            >
              {saving ? "Saving..." : "Save Book"}
            </button>
          </div>
        </div>
      </header>

      <div className="flex-1 flex flex-col overflow-hidden">
        <div className="flex-1 flex flex-col items-center justify-center p-4 overflow-auto min-h-0">
          <div className="flex items-center gap-2 mb-3 flex-wrap justify-center">
            <button
              onClick={() => {
                setAdjustingSlot(null);
                setCurrentPage((p) => Math.max(0, p - 1));
              }}
              disabled={currentPage === 0}
              className="px-3 py-1.5 rounded-lg border border-stone-300 text-sm disabled:opacity-40 hover:bg-white bg-white"
            >
              ← Prev
            </button>
            <div className="flex gap-1 max-w-[240px] sm:max-w-sm overflow-x-auto py-1">
              {pages.map((_, i) => (
                <button
                  key={i}
                  onClick={() => {
                    setAdjustingSlot(null);
                    setCurrentPage(i);
                  }}
                  className={`w-7 h-9 sm:w-8 sm:h-10 rounded border text-[10px] font-medium shrink-0 transition ${
                    i === currentPage
                      ? "border-orange-500 bg-orange-50 text-orange-700"
                      : "border-stone-300 bg-white text-stone-500 hover:border-stone-400"
                  }`}
                >
                  {i === 0 ? "C" : i}
                </button>
              ))}
            </div>
            <button
              onClick={() => {
                setAdjustingSlot(null);
                setCurrentPage((p) => Math.min(pages.length - 1, p + 1));
              }}
              disabled={currentPage === pages.length - 1}
              className="px-3 py-1.5 rounded-lg border border-stone-300 text-sm disabled:opacity-40 hover:bg-white bg-white"
            >
              Next →
            </button>
          </div>

          <div className="flex items-center gap-2 mb-2">
            <button
              type="button"
              onClick={() => setSpreadView((v) => !v)}
              className="px-3 py-1 rounded-full border border-stone-300 text-xs bg-white"
            >
              {spreadView ? "Single page" : "Two-page spread"}
            </button>
          </div>
          {isCover && (
            <div className="w-full max-w-md mb-2">
              <label className="text-xs text-stone-500 block mb-1">
                Cover text (names, date, message)
              </label>
              <input
                value={coverText}
                onChange={(e) => setCoverText(e.target.value)}
                placeholder="e.g. John & Mary · 12 June 2026"
                className="w-full px-3 py-2 rounded-lg border border-stone-200 text-sm outline-none focus:border-orange-500"
              />
            </div>
          )}
          <div
            className={`bg-white shadow-2xl rounded-sm border border-stone-300 overflow-hidden ${
              spreadView && !isCover
                ? "w-full max-w-3xl aspect-[2/1.2] flex"
                : "w-full max-w-md aspect-[3/4]"
            }`}
          >
            {spreadView && !isCover ? (
              <>
                <div className="flex-1 border-r border-stone-200 relative overflow-hidden">
                  {renderPageLayout()}
                </div>
                <div className="flex-1 relative overflow-hidden bg-stone-50 flex items-center justify-center text-xs text-stone-400 p-2">
                  {currentPage + 1 < pages.length ? (
                    <button
                      type="button"
                      className="underline"
                      onClick={() => setCurrentPage((p) => Math.min(pages.length - 1, p + 1))}
                    >
                      Facing page {currentPage + 2} — click Next to edit
                    </button>
                  ) : (
                    "End of book"
                  )}
                </div>
              </>
            ) : (
              renderPageLayout()
            )}
          </div>

          <p className="mt-3 text-xs text-stone-500 text-center max-w-sm">
            Drag photos into slots · Click <strong>⇄</strong> on a photo to zoom &
            reposition · Drag photos to rearrange · × to remove
          </p>
        </div>

        {/* Photo tray */}
        <div className="bg-white border-t border-stone-200 shrink-0">
          <div className="max-w-5xl mx-auto px-3 py-2 flex items-center justify-between">
            <div>
              <h2 className="font-semibold text-stone-800 text-sm">Your Photos</h2>
              <p className="text-xs text-stone-500">
                {photos.length} photo{photos.length !== 1 ? "s" : ""} · Drag into a
                slot above
              </p>
            </div>
            <Link href="/dashboard" className="text-xs text-orange-600 hover:underline">
              + Upload more
            </Link>
          </div>
          <div className="overflow-x-auto">
            <div className="flex gap-2 px-3 pb-3 min-w-min">
              {photos.length === 0 ? (
                <p className="text-xs text-stone-500 py-6 w-full text-center">
                  No photos yet.{" "}
                  <Link href="/dashboard" className="text-orange-600 underline">
                    Upload from Studio
                  </Link>
                </p>
              ) : (
                photos.map((photo) => {
                  const used = usedPhotoIds.has(photo.id);
                  return (
                    <div
                      key={photo.id}
                      draggable
                      onDragStart={() =>
                        setDragSource({ type: "library", photoId: photo.id })
                      }
                      onDragEnd={() => setDragSource(null)}
                      className={`w-20 h-20 sm:w-24 sm:h-24 rounded-lg overflow-hidden border cursor-grab active:cursor-grabbing transition relative shrink-0 ${
                        used
                          ? "border-orange-400 ring-2 ring-orange-200"
                          : "border-stone-200 hover:ring-2 hover:ring-orange-400"
                      }`}
                    >
                      <img
                        src={photo.url}
                        alt={photo.originalName || "Photo"}
                        className="w-full h-full object-cover pointer-events-none"
                      />
                      {used && (
                        <div className="absolute bottom-0 inset-x-0 bg-orange-600/85 text-white text-[9px] text-center py-0.5">
                          In book
                        </div>
                      )}
                    </div>
                  );
                })
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
