import { auth } from "@/lib/auth";
import { redirect, notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getTemplate } from "@/lib/templates";
import EditorClient from "./EditorClient";

export default async function ProjectEditorPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const session = await auth();
  if (!session?.user?.id) redirect("/login");

  const { id } = await params;

  const project = await prisma.project.findFirst({
    where: { id, userId: session.user.id },
    include: {
      projectPhotos: {
        include: { photo: true },
      },
    },
  });

  if (!project) notFound();

  const template = getTemplate(project.templateId);
  if (!template) notFound();

  // Also fetch all user photos so they can drag more into the book
  const allPhotos = await prisma.photo.findMany({
    where: { userId: session.user.id },
    orderBy: { createdAt: "desc" },
  });

  const pages = JSON.parse(project.pages || "[]");

  return (
    <EditorClient
      project={{
        id: project.id,
        title: project.title,
        templateId: project.templateId,
        status: project.status,
        pageCount: project.pageCount,
        autoGenerated: project.autoGenerated,
        coverColor: project.coverColor,
        pages,
      }}
      template={template}
      photos={allPhotos.map((p) => ({
        id: p.id,
        url: p.secureUrl || p.url,
        originalName: p.originalName,
      }))}
      userName={session.user.name || "User"}
    />
  );
}
