import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { getTemplate } from "@/lib/templates";
import { z } from "zod";

export async function GET() {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const projects = await prisma.project.findMany({
    where: { userId: session.user.id },
    orderBy: { updatedAt: "desc" },
  });

  return NextResponse.json(projects);
}

const createSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  templateId: z.string(),
  autoFill: z.boolean().optional().default(false),
  photoIds: z.array(z.string()).optional(),
});

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await req.json();
    const parsed = createSchema.safeParse(body);

    if (!parsed.success) {
      return NextResponse.json(
        { error: "Invalid input", details: parsed.error.flatten() },
        { status: 400 }
      );
    }

    const { title, templateId, autoFill, photoIds } = parsed.data;
    const template = getTemplate(templateId);

    if (!template) {
      return NextResponse.json({ error: "Template not found" }, { status: 404 });
    }

    // Only use photo IDs that actually belong to this user
    let photosToUse: string[] = [];
    if (autoFill && photoIds && photoIds.length > 0) {
      const validPhotos = await prisma.photo.findMany({
        where: {
          id: { in: photoIds },
          userId: session.user.id,
        },
        select: { id: true },
      });
      photosToUse = validPhotos.map((p) => p.id);
    }

    // Build pages and fill slots
    let photoIndex = 0;
    const pages = Array.from({ length: template.pages }, (_, i) => {
      const slots: (string | null)[] = Array(template.slotsPerPage).fill(null);

      if (photosToUse.length > 0) {
        for (let s = 0; s < template.slotsPerPage; s++) {
          if (photoIndex < photosToUse.length) {
            slots[s] = photosToUse[photoIndex];
            photoIndex++;
          }
        }
      }

      return {
        pageNum: i + 1,
        slots,
      };
    });

    const project = await prisma.project.create({
      data: {
        userId: session.user.id,
        title: title || `${template.name} Book`,
        templateId,
        pages: JSON.stringify(pages),
        pageCount: template.pages,
        autoGenerated: photosToUse.length > 0,
        status: "draft",
        coverColor: template.coverColor,
      },
    });

    // Link photos (only valid ones)
    if (photosToUse.length > 0) {
      try {
        await prisma.projectPhoto.createMany({
          data: photosToUse.map((photoId) => ({
            projectId: project.id,
            photoId,
          })),
          skipDuplicates: true,
        });
      } catch (linkError) {
        // Don't fail the whole request if linking fails
        console.error("Failed to link photos:", linkError);
      }
    }

    return NextResponse.json(project, { status: 201 });
  } catch (error: unknown) {
    console.error("Create project error:", error);
    return NextResponse.json(
      { error: (error instanceof Error ? error.message : null) || "Failed to create project" },
      { status: 500 }
    );
  }
}
