"use client";

import { useState, useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { TEMPLATES } from "@/lib/templates";

type Photo = {
  id: string;
  secureUrl: string;
  url: string;
  originalName: string | null;
  createdAt: string;
};

type Order = {
  id: string;
  amount: number;
  status: string;
  paymentStatus: string;
  bookSize: string;
  coverType: string;
  createdAt: string;
  project: { id: string; title: string };
};

type Project = {
  id: string;
  title: string;
  templateId: string;
  status: string;
  pageCount: number;
  autoGenerated: boolean;
  updatedAt: string;
};

export default function DashboardClient({ userName }: { userName: string }) {
  const router = useRouter();
  const [photos, setPhotos] = useState<Photo[]>([]);
  const [projects, setProjects] = useState<Project[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);
  const [uploading, setUploading] = useState(false);
  const [showCreate, setShowCreate] = useState(false);
  const [title, setTitle] = useState("");
  const [selectedTemplate, setSelectedTemplate] = useState(TEMPLATES[0].id);
  const [autoFill, setAutoFill] = useState(true);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Load photos and projects
  useEffect(() => {
    async function loadData() {
      try {
        const [photosRes, projectsRes, ordersRes] = await Promise.all([
          fetch("/api/photos"),
          fetch("/api/projects"),
          fetch("/api/orders"),
        ]);

        if (photosRes.ok) {
          const data = await photosRes.json();
          setPhotos(data);
        }
        if (projectsRes.ok) {
          const data = await projectsRes.json();
          setProjects(data);
        }
        if (ordersRes.ok) {
          const data = await ordersRes.json();
          setOrders(data);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    loadData();
  }, []);

  // Upload photos
  async function handleUpload(files: FileList | null) {
    if (!files || files.length === 0) return;
    setUploading(true);
    setError("");

    try {
      for (const file of Array.from(files)) {
        const reader = new FileReader();
        const dataUrl = await new Promise<string>((resolve, reject) => {
          reader.onload = () => resolve(reader.result as string);
          reader.onerror = reject;
          reader.readAsDataURL(file);
        });

        const res = await fetch("/api/photos", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            dataUrl,
            originalName: file.name,
          }),
        });

        if (res.ok) {
          const newPhoto = await res.json();
          setPhotos((prev) => [newPhoto, ...prev]);
        } else {
          const data = await res.json();
          setError(data.error || "Upload failed");
        }
      }
    } catch {
      setError("Failed to upload photos");
    } finally {
      setUploading(false);
    }
  }

  // Create project
  
  async function handleDeleteProject(projectId: string, title: string) {
    if (!confirm(`Delete photo book "${title}"? This cannot be undone.`)) return;
    try {
      const res = await fetch(`/api/projects/${projectId}`, { method: "DELETE" });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        alert(data.error || "Could not delete");
        return;
      }
      setProjects((prev) => prev.filter((p) => p.id !== projectId));
    } catch {
      alert("Could not delete photo book");
    }
  }

async function handleCreate() {
    setCreating(true);
    setError("");

    try {
      const res = await fetch("/api/projects", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: title || undefined,
          templateId: selectedTemplate,
          autoFill,
          photoIds: autoFill ? photos.map((p) => p.id) : [],
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || data.message || "Failed to create book");
        setCreating(false);
        return;
      }

      setShowCreate(false);
      setTitle("");
      setProjects((prev) => [data, ...prev]);
    } catch (err: unknown) {
      console.error("Create error:", err);
      setError((err instanceof Error ? err.message : undefined) || "Something went wrong. Check the terminal for details.");
    } finally {
      setCreating(false);
    }
  }

  const selectedTmpl = TEMPLATES.find((t) => t.id === selectedTemplate);

  return (
    <div className="min-h-screen bg-stone-100">
      <div className="bg-orange-800 text-orange-50 text-xs py-1.5">
        <div className="max-w-6xl mx-auto px-4 flex flex-wrap justify-between gap-2">
          <span>Chola Chela Photo Book Studio · Kitwe, Zambia</span>
          <span className="opacity-90">Your design studio</span>
        </div>
      </div>

      <nav className="border-b border-stone-200 bg-white sticky top-0 z-40 shadow-sm">
        <div className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between gap-4">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-full bg-orange-700 text-white flex items-center justify-center font-bold text-lg">
              CC
            </div>
            <div>
              <div className="font-semibold text-stone-900 leading-tight">
                Chola Chela
              </div>
              <div className="text-[10px] uppercase tracking-widest text-orange-700">
                Photo Book Studio
              </div>
            </div>
          </Link>
          <div className="flex items-center gap-3">
            <span className="text-sm text-stone-600 hidden sm:inline">
              Hi, <span className="font-medium text-stone-900">{userName}</span>
            </span>
            <Link
              href="/api/auth/signout?callbackUrl=/"
              className="text-sm px-3 py-1.5 rounded-full border border-stone-200 text-stone-600 hover:border-orange-400 hover:text-orange-800"
            >
              Log out
            </Link>
          </div>
        </div>
      </nav>

      <main className="max-w-6xl mx-auto px-4 py-10">
        <div className="rounded-3xl bg-gradient-to-br from-orange-700 via-orange-600 to-amber-600 text-white p-6 md:p-8 mb-8 shadow-md">
          <h1 className="text-2xl md:text-3xl font-bold">My Studio</h1>
          <p className="text-orange-100 mt-2 max-w-xl">
            Welcome back, {userName}. Design beautiful photo books with Chola
            Chela Photo Book Studio — upload photos, choose templates, and
            order print-ready albums.
          </p>
        </div>

        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
          <div>
            <h2 className="text-lg font-semibold text-stone-900">Your workspace</h2>
            <p className="text-sm text-stone-500">
              Create, edit and order photo books
            </p>
          </div>
          <div className="flex gap-3">
            {photos.length > 0 && (
              <button
                onClick={() => {
                  setAutoFill(true);
                  setShowCreate(true);
                }}
                className="px-5 py-2.5 rounded-full border-2 border-orange-600 text-orange-700 font-medium hover:bg-orange-50 transition"
              >
                ⚡ Auto-create Book
              </button>
            )}
            <button
              onClick={() => {
                setAutoFill(false);
                setShowCreate(true);
              }}
              className="px-5 py-2.5 rounded-full bg-orange-700 text-white font-medium hover:bg-orange-800 transition"
            >
              + New Photo Book
            </button>
          </div>
        </div>

        {error && (
          <div className="mb-6 text-sm text-red-600 bg-red-50 px-4 py-3 rounded-xl">
            {error}
          </div>
        )}

        <div className="grid lg:grid-cols-3 gap-8">
          {/* Projects */}
          <div className="lg:col-span-2 space-y-6">
            <section>
              <h2 className="font-semibold text-stone-800 mb-4">Your Photo Books</h2>

              {loading ? (
                <p className="text-stone-500">Loading...</p>
              ) : projects.length === 0 ? (
                <div className="rounded-2xl border border-dashed border-stone-300 p-12 text-center text-stone-500">
                  <p className="mb-2 text-lg font-medium text-stone-700">No photo books yet</p>
                  <p className="mb-5 text-sm">
                    Upload some photos, then let the system create a book for you automatically.
                  </p>
                  <button
                    onClick={() => setShowCreate(true)}
                    className="px-5 py-2.5 rounded-full bg-orange-700 text-white font-medium hover:bg-orange-800 transition"
                  >
                    {photos.length > 0 ? "Auto-create my first book" : "Create your first book"}
                  </button>
                </div>
              ) : (
                <div className="space-y-3">
                  {projects.map((p) => {
                    const tmpl = TEMPLATES.find((t) => t.id === p.templateId);
                    return (
                      <div
                        key={p.id}
                        className="flex items-center gap-4 p-4 rounded-xl bg-white border border-stone-200 hover:border-orange-300 hover:shadow-md transition"
                      >
                        <div
                          className={`w-16 h-20 rounded-lg flex-shrink-0 ${tmpl?.preview || "bg-stone-200"}`}
                        ></div>
                        <div className="flex-1 min-w-0">
                          <h3 className="font-medium text-stone-900 truncate">{p.title}</h3>
                          <p className="text-xs text-stone-500">
                            {tmpl?.name} · {p.pageCount} pages · {p.status}
                            {p.autoGenerated && " · Auto-created"}
                          </p>
                          <p className="text-xs text-stone-400 mt-0.5">
                            Updated {new Date(p.updatedAt).toLocaleDateString()}
                          </p>
                        </div>
                        <div className="flex flex-col gap-2 shrink-0">
                          <button
                            onClick={() => router.push(`/dashboard/projects/${p.id}`)}
                            className="px-3 py-1.5 text-sm rounded-lg bg-orange-700 text-white hover:bg-orange-800"
                          >
                            Open
                          </button>
                          <button
                            type="button"
                            onClick={() => handleDeleteProject(p.id, p.title)}
                            className="px-3 py-1.5 text-sm rounded-lg border border-red-200 text-red-600 hover:bg-red-50"
                          >
                            Delete
                          </button>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </section>

              {/* Orders */}
              {orders.length > 0 && (
                <section className="mt-8">
                  <h2 className="font-semibold text-stone-800 mb-4">Your Orders</h2>
                  <div className="space-y-3">
                    {orders.map((o) => (
                      <div
                        key={o.id}
                        className="flex items-center gap-4 p-4 rounded-xl bg-white border border-stone-200"
                      >
                        <div className="flex-1 min-w-0">
                          <h3 className="font-medium text-stone-900 truncate">
                            {o.project?.title || "Photo Book"}
                          </h3>
                          <p className="text-xs text-stone-500">
                            {o.bookSize} · {o.coverType} ·{" "}
                            <span className="capitalize">{o.status}</span> ·{" "}
                            <span className="capitalize">{o.paymentStatus}</span>
                          </p>
                          <p className="text-xs text-stone-400 mt-0.5">
                            {new Date(o.createdAt).toLocaleDateString()}
                          </p>
                        </div>
                        <div className="text-right">
                          <div className="font-semibold text-stone-900">
                            K{(o.amount / 100).toFixed(2)}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </section>
              )}
          </div>

          {/* Photo Library */}
          <div>
            <h2 className="font-semibold text-stone-800 mb-4">Photo Library</h2>

            {/* Upload zone */}
            <div
              onClick={() => fileInputRef.current?.click()}
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => {
                e.preventDefault();
                handleUpload(e.dataTransfer.files);
              }}
              className="border-2 border-dashed border-stone-300 rounded-2xl p-6 text-center cursor-pointer hover:border-orange-400 hover:bg-orange-50/50 transition mb-4"
            >
              <div className="text-3xl mb-2">📤</div>
              <p className="font-medium text-stone-700 text-sm">
                {uploading ? "Uploading..." : "Drop photos here or click to browse"}
              </p>
              <p className="text-xs text-stone-500 mt-1">JPG, PNG</p>
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                multiple
                className="hidden"
                onChange={(e) => handleUpload(e.target.files)}
              />
            </div>

            {/* Photos grid */}
            {photos.length === 0 ? (
              <p className="text-sm text-stone-500 text-center py-4">No photos uploaded yet</p>
            ) : (
              <div className="grid grid-cols-3 gap-2 max-h-96 overflow-y-auto">
                {photos.map((p) => (
                  <div
                    key={p.id}
                    className="aspect-square rounded-lg overflow-hidden border border-stone-200 bg-stone-100"
                  >
                    <img
                      src={p.secureUrl || p.url}
                      alt={p.originalName || "Photo"}
                      className="w-full h-full object-cover"
                    />
                  </div>
                ))}
              </div>
            )}
            {photos.length > 0 && (
              <p className="text-xs text-stone-500 mt-2 text-center">{photos.length} photo(s)</p>
            )}
          </div>
        </div>
      </main>

      <footer className="border-t border-stone-200 bg-white">
        <div className="max-w-6xl mx-auto px-4 py-6 text-center text-xs text-stone-500">
          <span className="font-medium text-stone-700">Chola Chela Photography</span>
          {" · "}
          Photo Book Studio · Kitwe, Zambia
          <br />
          <a
            href="https://wa.me/260966080108"
            className="text-orange-700 hover:underline"
            target="_blank"
            rel="noreferrer"
          >
            WhatsApp +260 966 080 108
          </a>
        </div>
      </footer>

      {/* Create Book Modal */}
      {showCreate && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full p-6">
            <h2 className="text-xl font-bold mb-4">Create new photo book</h2>

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">Book title</label>
                <input
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g. Our Family 2025"
                  className="w-full px-4 py-2.5 rounded-xl border border-stone-200 focus:border-orange-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">Choose template</label>
                <div className="grid grid-cols-2 gap-2 max-h-48 overflow-y-auto">
                  {TEMPLATES.map((t) => (
                    <button
                      key={t.id}
                      type="button"
                      onClick={() => setSelectedTemplate(t.id)}
                      className={`text-left p-3 rounded-xl border text-sm ${
                        selectedTemplate === t.id
                          ? "border-orange-500 bg-orange-50"
                          : "border-stone-200 hover:border-stone-300"
                      }`}
                    >
                      <div className="font-medium">{t.name}</div>
                      <div className="text-xs text-stone-500">{t.pages} pages</div>
                    </button>
                  ))}
                </div>
              </div>

              <label className="flex items-center gap-3 cursor-pointer">
                <input
                  type="checkbox"
                  checked={autoFill}
                  onChange={(e) => setAutoFill(e.target.checked)}
                  className="w-4 h-4 rounded border-stone-300 text-orange-600"
                />
                <div>
                  <div className="text-sm font-medium text-stone-800">Auto-fill with my photos</div>
                  <div className="text-xs text-stone-500">
                    {photos.length === 0
                      ? "Upload photos first to enable this"
                      : `Will place up to ${Math.min(
                          photos.length,
                          (selectedTmpl?.pages || 0) * (selectedTmpl?.slotsPerPage || 0)
                        )} of your ${photos.length} photos`}
                  </div>
                </div>
              </label>
            </div>

            <div className="flex gap-3 mt-6">
              <button
                onClick={() => setShowCreate(false)}
                className="flex-1 py-2.5 rounded-xl border border-stone-200 font-medium"
              >
                Cancel
              </button>
              <button
                onClick={handleCreate}
                disabled={creating || (autoFill && photos.length === 0)}
                className="flex-1 py-2.5 rounded-xl bg-orange-700 text-white font-medium hover:bg-orange-800 disabled:opacity-50"
              >
                {creating
                  ? "Creating..."
                  : autoFill && photos.length > 0
                  ? "Auto-create Book"
                  : "Create Empty Book"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
